require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
